### ISSUE TITLE
Visual Studio Code syntax highlighter

### ISSUE THREAD

**Issue by dahlia** [spoqa/nirum#158]

**Comment by qria** [comment]
[Done.](https://marketplace.visualstudio.com/items?itemName=Nirum.nirum-syntax-highlighting)

<img width="323" alt="nirum-highlighter-screenshot" src="https://user-images.githubusercontent.com/4233072/37251249-dfd90bdc-254f-11e8-84e6-6d075bd24ab3.png">

**Comment by dahlia** [comment]
👍👏
