### ISSUE TITLE
Make nirum-wsgi independent from Werkzeug

### ISSUE THREAD

**Issue by dahlia** [spoqa/nirum#284]
The current WSGI implementation does not use any features Werkzeug provides.  Only its test suite and a tiny CLI program for dev depend on Werkzeug.  Requiring Werkzeug for every case seems overkill.

**Comment by dahlia** [comment]
> The current WSGI implementation does not use any features Werkzeug provides.

It still uses `Request` and `Response` objects from Werkzeug.  It's my misremembering. /cc @admire93

**Comment by admire93** [comment]
- https://github.com/spoqa/nirum-python-wsgi/blob/0.3-maintenance/nirum_wsgi.py#L252
- https://github.com/spoqa/nirum-python-wsgi/blob/0.3-maintenance/nirum_wsgi.py#L590
