### ISSUE TITLE
Suggest renaming boxed keyword to unboxed

### ISSUE THREAD

**Issue by dahlia** [spoqa/nirum#65]
As @Kroisse previously addressed by word of mouth, the meaning of `boxed` is misleading since `boxed` types are actually not boxed when it comes to JSON!

So I suggest: how about renaming `boxed` keyword to `unboxed`?  Although it becomes two letters longer, I believe it would be more predictable and less misleading.

**Comment by Kroisse** [comment]
I think that it's not necessary to imply its implementation details on the keyword name, so neither `boxed` nor `unboxed` are inappropriate.

**Comment by dahlia** [comment]
@Kroisse I'm not with you. How types are serialized in JSON are not just implementation detail, but sort of what users have to be aware of.  If it's just implementation detail we should remove `enum` and `boxed` because they can be generalized using `union` and `record`.

**Comment by dahlia** [comment]
Although there could be better alternatives to `unboxed`, I believe `unboxed` is way better than `boxed` at least.  If we don't have enough time to search better candidates than `unboxed` I still suggest to rename `boxed` to `unboxed`. (@admire93 has coded that uses `boxed` keyword at @spoqa, and we're getting less opportune to rename it day by day.)
